# Generated by Django 2.1.7 on 2025-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('engagement_desc', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('engagement_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('teaching_subjects', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('course_year', models.CharField(max_length=10)),
                ('result_description', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('paper_title', models.CharField(max_length=255)),
                ('author_list', models.CharField(max_length=255)),
                ('journal_name', models.CharField(max_length=255)),
                ('issue_no', models.CharField(max_length=10)),
                ('total_pages', models.CharField(max_length=10)),
                ('publisher_name', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('indexing', models.CharField(max_length=100)),
                ('doi_no', models.CharField(max_length=255)),
                ('publish_url', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('course_year', models.CharField(max_length=10)),
                ('lecture_room', models.CharField(max_length=10)),
                ('covering_topic', models.CharField(max_length=255)),
                ('lecture_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=255)),
                ('course_year', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
