# Generated by Django 2.1.7 on 2025-01-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engagement',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
