# Generated by Django 2.1.7 on 2025-01-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_faculty_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=40)),
                ('engagement_desc', models.CharField(max_length=40)),
                ('from_date', models.CharField(max_length=30)),
                ('to_date', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('engagement_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'engagement',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('course_year', models.CharField(max_length=40)),
                ('result_description', models.CharField(max_length=40)),
                ('sheet_name', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('paper_title', models.CharField(max_length=80)),
                ('aurhor_list', models.CharField(max_length=80)),
                ('journal_name', models.CharField(max_length=30)),
                ('issue_no', models.CharField(max_length=50)),
                ('total_pages', models.CharField(max_length=50)),
                ('publisher_name', models.CharField(max_length=50)),
                ('publish_date', models.CharField(max_length=40)),
                ('indexing', models.CharField(max_length=20)),
                ('doi_no', models.CharField(max_length=30)),
                ('publish_url', models.CharField(max_length=60)),
                ('filename', models.CharField(max_length=50)),
                ('upload_date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('course_year', models.CharField(max_length=40)),
                ('lecture_room', models.CharField(max_length=40)),
                ('covering_topic', models.CharField(max_length=100)),
                ('lecture_date', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
